version: '3'

services:
    front-dev:
        container_name: front-dev
        build:
            context: .
            dockerfile: Dockerfile.dev    
        working_dir: /app
        command: sh -c "yarn && yarn run many:start"
        ports:
            - 8080:8080
            - 8081:8081
        volumes:
            - .:/app
        restart: always

    # front-prod:
    #     container_name: front-prod
    #     build:
    #         context: .
    #         dockerfile: Dockerfile.prod
    #     working_dir: /app
    #     command: sh -c "yarn && yarn run build && serve -s build"
    #     ports:
    #         - "4200:4200"
    #     volumes:
    #         - .:/app

