version: '3'

services:
    front-dev:
        container_name: front-dev
        build:
            context: .
            dockerfile: Dockerfile.dev    
        working_dir: /app
        command: sh -c "yarn && yarn run start"
        ports:
            - "4200:8080"
        volumes:
            - .:/app
    front-build:
        container_name: front-build
        build:
            context: .
            dockerfile: Dockerfile.build    
        working_dir: /app
        command: sh -c "yarn && yarn run build && serve -s build"
    
        ports:
            - "4200:8080"
        volumes:
            - .:/app

