version: '3'

services:
    front-dev:
        container_name: front-dev
        build:
            context: .
            dockerfile: Dockerfile.dev    
        working_dir: /app
        command: sh -c "yarn && yarn start "
        ports:
            - "4200:4200"
        volumes:
            - .:/app
        env_file:
            - .env
    front-build:
        container_name: front-build
        build:
            context: .
            dockerfile: Dockerfile.build    
        working_dir: /app
        command: sh -c "yarn && yarn run build && serve -s build"

        ports:
            - "4200:4200"
        volumes:
            - .:/app
        env_file:
            - .env

